import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:tripgenie/features/planner/models/itinerary_model.dart';

/// PDF export service for itineraries.
/// Generates a print-ready PDF document from an Itinerary object.
class PdfExportService {
  /// Generate and show print/share dialog for an itinerary
  static Future<void> exportItinerary(BuildContext context, Itinerary itinerary) async {
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async {
        return Uint8List.fromList(await _buildPdf(itinerary, format));
      },
    );
  }

  /// Share itinerary as PDF
  static Future<void> shareItinerary(Itinerary itinerary) async {
    await Printing.sharePdf(
      bytes: Uint8List.fromList(await _buildPdf(itinerary, PdfPageFormat.a4)),
      filename: '${itinerary.destination.replaceAll(' ', '_')}_itinerary.pdf',
    );
  }

  static Future<List<int>> _buildPdf(Itinerary itinerary, PdfPageFormat format) async {
    final pdf = pw.Document(
      title: '${itinerary.destination} – ${itinerary.days}-Day Itinerary',
      author: 'TripGenie / WanderLand',
    );

    // Accent color
    final accentColor = PdfColor.fromHex('#1A73E8');
    final greenColor = PdfColor.fromHex('#00C897');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        margin: const pw.EdgeInsets.all(40),
        header: (pw.Context context) {
          return pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('WanderLand', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              pw.Text('Page ${context.pageNumber}/${context.pagesCount}',
                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
            ],
          );
        },
        footer: (pw.Context context) {
          return pw.Center(
            child: pw.Text(
              'Generated by TripGenie AI • ${DateTime.now().toIso8601String().split('T').first}',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
            ),
          );
        },
        build: (pw.Context context) {
          return [
            // Title block
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                color: accentColor,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    itinerary.destination,
                    style: pw.TextStyle(
                      fontSize: 28,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white,
                    ),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Text(
                    itinerary.summary,
                    style: pw.TextStyle(fontSize: 12, color: PdfColor.fromHex('#FFFFFFB0')),
                  ),
                  pw.SizedBox(height: 14),
                  pw.Row(
                    children: [
                      _pdfInfoChip('${itinerary.days} Days'),
                      pw.SizedBox(width: 12),
                      _pdfInfoChip('\$${itinerary.budget.toStringAsFixed(0)} Budget'),
                    ],
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 24),

            // Day-by-day plans
            ...itinerary.dayPlans.map((dayPlan) {
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  // Day header
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                    decoration: pw.BoxDecoration(
                      color: greenColor,
                      borderRadius: pw.BorderRadius.circular(6),
                    ),
                    child: pw.Text(
                      'Day ${dayPlan.day} – ${dayPlan.date}',
                      style: pw.TextStyle(
                        fontSize: 14,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.white,
                      ),
                    ),
                  ),
                  pw.SizedBox(height: 10),

                  // Activities
                  ...dayPlan.activities.map((activity) {
                    return pw.Padding(
                      padding: const pw.EdgeInsets.only(bottom: 10, left: 8),
                      child: pw.Row(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Container(
                            width: 60,
                            child: pw.Text(
                              activity.time,
                              style: pw.TextStyle(
                                fontSize: 10,
                                fontWeight: pw.FontWeight.bold,
                                color: accentColor,
                              ),
                            ),
                          ),
                          pw.Expanded(
                            child: pw.Column(
                              crossAxisAlignment: pw.CrossAxisAlignment.start,
                              children: [
                                pw.Text(
                                  activity.title,
                                  style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
                                ),
                                pw.SizedBox(height: 2),
                                pw.Text(
                                  activity.description,
                                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    );
                  }),

                  pw.SizedBox(height: 12),
                ],
              );
            }),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _pdfInfoChip(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#FFFFFF30'),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 10, color: PdfColors.white, fontWeight: pw.FontWeight.bold),
      ),
    );
  }
}
